apiVersion: v1
kind: Service
metadata:
  name: node-example-service
  labels:
    app: node-example-app
spec:
  type: LoadBalancer
  selector:
    app: node-example-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
