version: '3.2'

volumes:
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:6.6.2
    user: "472" #username: admin  password: password
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
    depends_on:
      - prometheus
  server:
    image: node:erbium-alpine
    working_dir: /server
    command: npm start
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./server
        target: /server
  server-1:
    image: node:erbium-alpine
    working_dir: /server
    command: npm start
    ports:
      - 5001:5000
    volumes:
      - type: bind
        source: ./server
        target: /server
